// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzFPzlakGRQ3dcNXY1S6XoeIL9tI2NPIE',
    appId: '1:1006591054193:web:0338e02f0db8a2cf2f66d0',
    messagingSenderId: '1006591054193',
    projectId: 'report-app-91ba3',
    authDomain: 'report-app-91ba3.firebaseapp.com',
    storageBucket: 'report-app-91ba3.firebasestorage.app',
    measurementId: 'G-D3GTNWC83P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6qF1RMi8wEKncPDjfoMt11-X74k0-7rg',
    appId: '1:1006591054193:android:ab3f4a7d965c97b62f66d0',
    messagingSenderId: '1006591054193',
    projectId: 'report-app-91ba3',
    storageBucket: 'report-app-91ba3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZtVZ_5Z2EVQcjTb2DEXgHsWWRyDdXLA0',
    appId: '1:1006591054193:ios:6c78aeea35819ec02f66d0',
    messagingSenderId: '1006591054193',
    projectId: 'report-app-91ba3',
    storageBucket: 'report-app-91ba3.firebasestorage.app',
    iosBundleId: 'com.example.reportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZtVZ_5Z2EVQcjTb2DEXgHsWWRyDdXLA0',
    appId: '1:1006591054193:ios:6c78aeea35819ec02f66d0',
    messagingSenderId: '1006591054193',
    projectId: 'report-app-91ba3',
    storageBucket: 'report-app-91ba3.firebasestorage.app',
    iosBundleId: 'com.example.reportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzFPzlakGRQ3dcNXY1S6XoeIL9tI2NPIE',
    appId: '1:1006591054193:web:39ea5d8cce8cb64d2f66d0',
    messagingSenderId: '1006591054193',
    projectId: 'report-app-91ba3',
    authDomain: 'report-app-91ba3.firebaseapp.com',
    storageBucket: 'report-app-91ba3.firebasestorage.app',
    measurementId: 'G-LMYFLJNPBX',
  );

}