// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJmOos2XzcFT23RaIl1Q6w1I0-Cv3MU4w',
    appId: '1:682544591515:web:7440cb1d529915b9750c3e',
    messagingSenderId: '682544591515',
    projectId: 'report-app-b4839',
    authDomain: 'report-app-b4839.firebaseapp.com',
    storageBucket: 'report-app-b4839.firebasestorage.app',
    measurementId: 'G-8V85DXW6BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy8o5JIV6nZY_gGkZbpn9ddIr2txe8TgQ',
    appId: '1:682544591515:android:e8657ea68a7b9ad2750c3e',
    messagingSenderId: '682544591515',
    projectId: 'report-app-b4839',
    storageBucket: 'report-app-b4839.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdSrS3RQRumxMPv3DfCo7aaZv3fQfecrI',
    appId: '1:682544591515:ios:e91e1224d9348dc7750c3e',
    messagingSenderId: '682544591515',
    projectId: 'report-app-b4839',
    storageBucket: 'report-app-b4839.firebasestorage.app',
    iosBundleId: 'com.example.reportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdSrS3RQRumxMPv3DfCo7aaZv3fQfecrI',
    appId: '1:682544591515:ios:e91e1224d9348dc7750c3e',
    messagingSenderId: '682544591515',
    projectId: 'report-app-b4839',
    storageBucket: 'report-app-b4839.firebasestorage.app',
    iosBundleId: 'com.example.reportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJmOos2XzcFT23RaIl1Q6w1I0-Cv3MU4w',
    appId: '1:682544591515:web:3b6b23c5a05f7bd0750c3e',
    messagingSenderId: '682544591515',
    projectId: 'report-app-b4839',
    authDomain: 'report-app-b4839.firebaseapp.com',
    storageBucket: 'report-app-b4839.firebasestorage.app',
    measurementId: 'G-QNC2SNREL9',
  );
}
